I_Volenteer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('NLP.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

NLP/urls.py
from django.urls import path

from . import views, text2info

app_name = 'NLP'
urlpatterns = [
    path('', views.home, name='home'),
    path('maps/',views.maps,name='maps'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('test/',views.index,name='index'),
    path('upload/',views.upload,name='upload'),
    path('manual_entry/', views.manual_entry, name='manual_entry'),
    path('audio_data/', views.audio_data, name='audio_data'),
    path('new_profile/',views.update_profile,name='new_profile'),
    path('create_profile/',views.create_profile,name='create_profile')
]

NLP/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class NLP_MAPS(models.Model):
    id = models.IntegerField(primary_key=True)
    x = models.FloatField() 
    y = models.FloatField()
    Address = models.TextField()
    intensity = models.IntegerField()
    Remarks = models.CharField(max_length=50,default='Road Block',)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.Address 

class Organisation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.CharField(max_length=100,default='NITK Rescue Team')
    def __str__(self):
        return self.organisation

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Organisation.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.organisation.save()

NLP/forms.py
from django import forms
from django.contrib.auth.models import User
from NLP.models import NLP_MAPS, Organisation

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class OrganisationForm(forms.ModelForm):
    class Meta:
        model = Organisation
        fields = ('organisation',)

NLP/views.py
#importing neccessary libraries
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from NLP.forms import UserForm, OrganisationForm
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm

from NLP.models import NLP_MAPS
# Create your views here.
import googlemaps
from . import text2info , audio2text

from .models import NLP_MAPS
#method for index file
def index(converted_text,current_user):
    template = 'NLP/index.html'
    map = NLP_MAPS()
    res = {}
    res = text2info.get_info(converted_text)
    print("here ", res)
    gmaps = googlemaps.Client(key='AIzaSyCQQIUtvPUSukJ93gTexnAnz1uqXkz79MI')
    print("kiops")
    geocode_result = gmaps.geocode(res['Address'])
    print("asaasa")
    print(geocode_result)
    # print(geocode_result)
    map.user_id = current_user
    map.Address = res['Address']
    map.x = geocode_result[0]['geometry']['location']['lat']
    map.y = geocode_result[0]['geometry']['location']['lng']
    map.intensity = res['Intensity']
    map.Remarks = res['Remark']
    map.save()
    return

def dashboard(request):
    address = NLP_MAPS.objects.all()
    return render(request,'dashboard.html',{'address': address})

def manual_entry(request):
    if request.method == 'POST':
        print(request.POST['name'] )
        print(request.POST['remark'])
        print(request.user)
        gmaps = googlemaps.Client(key='AIzaSyCQQIUtvPUSukJ93gTexnAnz1uqXkz79MI')
        geocode_result = gmaps.geocode(request.POST['name'])
        print(geocode_result)
        map = NLP_MAPS()
        map.Address = request.POST['name']
        map.x = geocode_result[0]['geometry']['location']['lat']
        map.y = geocode_result[0]['geometry']['location']['lng']
        map.intensity = 2
        map.Remarks = request.POST['remark']
        map.user_id = request.user
        map.save()
        return render(request,'Home/home.html')
    else:
        return render(request,'Home/home.html')

@csrf_exempt
def audio_data(request):
    if request.method == 'POST':
        print(request.POST['send'])
        gmaps = googlemaps.Client(key='AIzaSyCQQIUtvPUSukJ93gTexnAnz1uqXkz79MI')
        geocode_result = gmaps.geocode(request.POST['send'])
        print(geocode_result)
        map = NLP_MAPS()
        map.user_id = request.user
        map.Address = request.POST['send']
        map.x = geocode_result[0]['geometry']['location']['lat']
        map.y = geocode_result[0]['geometry']['location']['lng']
        map.intensity = 2
        map.Remarks = 2
        map.save()
        print("jio")
    else:
        print("get")
    message = "hello"
    return HttpResponse(message)


def home(request):
    user = User.objects.get(pk=1)
    print(user.organisation.organisation)
    return render(request,'Home/home.html')

def maps(request):
    address = NLP_MAPS.objects.values('id','x','y','Address')
    # serial = serializers.serialize('json', [ address, ])
    json_data = json.dumps(list(address))
    return render(request,'NLP/maps.html',{'address':json_data})


def upload(request):
    print("Started Uplaod")
    if request.method == 'POST' and request.FILES['myfile']:
        # print("ywuueiwi")
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()

        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        print("sending file to Speech to Text API")
        converted_text = audio2text.get_text_from_audio(uploaded_file_url)
        print("Computed Text Recieved")
        current_user = request.user
        index(converted_text,current_user)
        # file_path = os.path.join(BASE_DIR, uploaded_file_url)
        # pass_file_path(file_path)
        # index()
        print(uploaded_file_url)
        return render(request, 'NLP/index.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'NLP/upload.html')

    if request.method == 'GET':
        print("jujdsd .....")
        return render(request, 'NLP/upload.html')

@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = OrganisationForm(request.POST, instance=request.user.organisation)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return render(request,'Home/home.html')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = OrganisationForm(instance=request.user.organisation)
    return render(request, 'profiles/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def create_profile(request):
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        # profile_form = OrganisationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            # profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return render(request,'registration/login.html')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserCreationForm()
        # profile_form = OrganisationForm()
    return render(request, 'profiles/new.html', {
        'user_form': user_form,
        # 'profile_form': profile_form
    })

NLP/templates/NLP/index.html
<!doctype html>
<html lang="en">
  <head>
    <title>I_volunteer</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Sacramento" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static "NLP/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/owl.carousel.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/ionicons/css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "NLP/fonts/fontawesome/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/flaticon/font/flaticon.css" %} ">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static "NLP/css/style.css" %} ">
  </head>
  <body>
    
    <header role="banner">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'NLP:home' %}">I_Volunteer</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'NLP:home' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://www.nsdma.gov.in/" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Donate</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href="https://www.karnatakaone.gov.in/">Karanatka Relief</a>
                  <a class="dropdown-item" href="http://www.nsdma.gov.in/">Nagaland Relief</a>
                  <a class="dropdown-item" href="https://donation.cmdrf.kerala.gov.in/">Kerel Relief</a>
                </div>

              </li>
              {% if user.is_authenticated %}

              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'NLP:dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'NLP:maps' %}">Maps</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'NLP:upload' %}">Upload</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" >Hi {{ user.username }}</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">logout</a>
              </li>                
                  {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">login</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:create_profile' %}">Sign up</a>
                  </li>              
                  {% endif %}
            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    <!-- END header -->

    <div class="container" style="margin:10%">  
      {% block content %}
      {% if uploaded_file_url %}
      <h1>File Successfully Uploaded</h1>
      {% comment %} <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p> {% endcomment %}
      {% endif %}
      <p>
        Go to <a href="{% url 'NLP:dashboard' %}" >Dashboard</a>
      </p>
    </div>
    {% endblock %}


    <footer class="site-footer" role="contentinfo">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-3 mb-5">
            <h3>About</h3>
            <p>Effort to crete a change in society for helping others</p>
            <p><a href="#">Learn More</a></p>
          </div>
          <div class="col-md-3">
            <h3>Contact &amp; Address</h3>
            <ul class="list-unstyled footer-link">
              <li class="d-flex"><span class="mr-3">A:</span><span class="text-white">NITK Hostels,NITK</span></li>
              <li class="d-flex"><span class="mr-3">T:</span><span class="text-white">+91 9404239451</span></li>
              <li class="d-flex"><span class="mr-3">E:</span><span class="text-white">contact@ivolunteer.nitk.edu.in</span></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 text-md-center text-left">

            <p>This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">I_Volunteer Team</a></p>
          </div>
        </div>
      </div>
    </footer>
    <!-- END footer -->

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'NLP/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'NLP/js/popper.min.js' %}"></script>
    <script src="{% static 'NLP/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'NLP/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'NLP/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'NLP/js/main.js' %}"></script>
  </body>
</html>

NLP/templates/NLP/maps.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Display markers</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Sacramento" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static "NLP/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/owl.carousel.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/ionicons/css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "NLP/fonts/fontawesome/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/flaticon/font/flaticon.css" %} ">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static "NLP/css/style.css" %} ">
</head>
    <style>
        #map {
          height: 100%;
        }
        html, body {
          height: 100%;
          margin: 0;
          padding: 0;
        }
    </style>
<body>
    <header role="banner">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
            <a class="navbar-brand" href="{% url 'NLP:home' %}">I_Volunteer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://www.nsdma.gov.in/" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Donate</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <a class="dropdown-item" href="https://www.karnatakaone.gov.in/">Karanatka Relief</a>
                    <a class="dropdown-item" href="http://www.nsdma.gov.in/">Nagaland Relief</a>
                    <a class="dropdown-item" href="https://donation.cmdrf.kerala.gov.in/">Kerel Relief</a>
                    </div>
    
                    {% if user.is_authenticated %}

                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'NLP:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'NLP:maps' %}">Maps</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'NLP:upload' %}">Upload</a>
                </li>
                              <li class="nav-item">
                    <a class="nav-link" >Hi {{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                </li>                
                    {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">login</a>
                  </li>       
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'NLP:create_profile' %}">Sign up</a>
                      </li>        
                    {% endif %}
                </ul>
            </div>
            </div>
        </nav>
    </header>
    <div id="map" class="container"></div>
    <script>
            function initMap() {
                var myLatLng = {lat: 13.0108387	, lng: 74.7943104};
                var marker = new google.maps.Marker({
                  position: myLatLng,
                  map: map,
                  title: 'Hello World!'
                });
             var locations = {{address|safe}};
             var marker, i;
            console.log(locations)
             var map = new google.maps.Map(document.getElementById('map'), {
             zoom: 15,
             center: myLatLng
             });
             for (i = 0; i < locations.length; i++) { 
                 marker = new google.maps.Marker({
                     position: new google.maps.LatLng(locations[i]['x'], locations[i]['y']),
                     map: map,
                     title: locations[i]['Address']
                 });
            }
        }
    </script>
    <footer class="site-footer" role="contentinfo">
        <div class="container">
            <div class="row mb-5">
            <div class="col-md-3 mb-5">
                <h3>About</h3>
                <p>Effort to crete a change in society for helping others</p>
                <p><a href="#">Learn More</a></p>
            </div>
            <div class="col-md-3">
                <h3>Contact &amp; Address</h3>
                <ul class="list-unstyled footer-link">
                <li class="d-flex"><span class="mr-3">A:</span><span class="text-white">NITK Hostels,NITK</span></li>
                <li class="d-flex"><span class="mr-3">T:</span><span class="text-white">+91 9404239451</span></li>
                <li class="d-flex"><span class="mr-3">E:</span><span class="text-white">contact@ivolunteer.nitk.edu.in</span></li>
                </ul>
            </div>
            </div>
            <div class="row">
            <div class="col-12 text-md-center text-left">
    
                <p>This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">I_Volunteer Team</a></p>
            </div>
            </div>
        </div>
    </footer>
        <!-- END footer -->
    
        <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'NLP/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'NLP/js/popper.min.js' %}"></script>
    <script src="{% static 'NLP/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'NLP/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'NLP/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'NLP/js/main.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBt50Fsl9GeVl0DBf1RIWorWpVfVxdlAV8&callback=initMap">
    </script>
</body>
</html>

NLP/templates/base.html
<!doctype html>
<html lang="en">
<head>
        <title>I_volunteer</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800|Sacramento" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static "NLP/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "NLP/css/owl.carousel.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/ionicons/css/ionicons.min.css" %}">
    <link rel="stylesheet" href="{% static "NLP/fonts/fontawesome/css/font-awesome.min.css" %}">

    <link rel="stylesheet" href="{% static "NLP/fonts/flaticon/font/flaticon.css" %} ">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static "NLP/css/style.css" %} ">
    <style>
            h1{
                font-size: 30px;
                color: #fff;
                text-transform: uppercase;
                font-weight: 300;
                text-align: center;
                margin-bottom: 15px;
              }
              table{
                width:100%;
                table-layout: fixed;
              }
              .tbl-header{
                background-color: rgba(255,255,255,0.3);
               }
              .tbl-content{
                height:300px;
                overflow-x:auto;
                margin-top: 0px;
                border: 1px solid rgba(255,255,255,0.3);
              }
              th{
                padding: 20px 15px;
                text-align: left;
                font-weight: 500;
                font-size: 12px;
                color: #fff;
                text-transform: uppercase;
              }
              td{
                padding: 15px;
                text-align: left;
                vertical-align:middle;
                font-weight: 300;
                font-size: 12px;
                color: #fff;
                border-bottom: solid 1px rgba(255,255,255,0.1);
              }
              
              
              
              @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);

              section{
                margin: 50px;
              }
              .made-with-love {
                margin-top: 40px;
                padding: 10px;
                clear: left;
                text-align: center;
                font-size: 10px;
                font-family: arial;
                color: #fff;
              }
              .made-with-love i {
                font-style: normal;
                color: #F50057;
                font-size: 14px;
                position: relative;
                top: 2px;
              }
              .made-with-love a {
                color: #fff;
                text-decoration: none;
              }
              .made-with-love a:hover {
                text-decoration: underline;
              }
              
              ::-webkit-scrollbar {
                  width: 6px;
              } 
              ::-webkit-scrollbar-track {
                  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
              } 
              ::-webkit-scrollbar-thumb {
                  -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
              }
    </style>
</head>
<body>
    <header role="banner">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
            <a class="navbar-brand" href="{% url 'NLP:home' %}">I_Volunteer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarsExample05">
                <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'NLP:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="https://www.karnatakaone.gov.in/Info/Public/CalamityReliefFund" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Donate</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                    <a class="dropdown-item" href="https://www.karnatakaone.gov.in/Info/Public/CalamityReliefFund">Karanatka Relief</a>
                    <a class="dropdown-item" href="http://www.nsdma.gov.in/">Nagaland Relief</a>
                    <a class="dropdown-item" href="https://donation.cmdrf.kerala.gov.in/">Kerel Relief</a>
                    </div>
    
                    {% if user.is_authenticated %}

                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'NLP:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'NLP:maps' %}">Maps</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'NLP:upload' %}">Upload</a>
                </li>
                              <li class="nav-item">
                    <a class="nav-link" >Hi {{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">logout</a>
                </li>                
                    {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">login</a>
                  </li>              
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'NLP:create_profile' %}">Sign up</a>
                    </li> 
                    {% endif %}
                </ul>
            </div>
            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer class="site-footer">
            <div class="container">
              <div class="row mb-5">
                <div class="col-md-3 mb-5">
                  <h3>About</h3>
                  <p>Effort to crete a change in society for helping others</p>
                  <p><a href="#">Learn More</a></p>
                </div>
                <div class="col-md-3">
                  <h3>Contact &amp; Address</h3>
                  <ul class="list-unstyled footer-link">
                    <li class="d-flex"><span class="mr-3">A:</span><span class="text-white">NITK Hostels,NITK</span></li>
                    <li class="d-flex"><span class="mr-3">T:</span><span class="text-white">+91 9404239451</span></li>
                    <li class="d-flex"><span class="mr-3">E:</span><span class="text-white">contact@ivolunteer.nitk.edu.in</span></li>
                  </ul>
                </div>
              </div>
              <div class="row">
                <div class="col-12 text-md-center text-left">
      
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  <p>This website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#" target="_blank">Manas</a></p>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
              </div>
            </div>
          </footer>
          <!-- END footer -->
      
          <!-- loader -->
          <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>      
    <script src="{% static 'NLP/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'NLP/js/popper.min.js' %}"></script>
    <script src="{% static 'NLP/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'NLP/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'NLP/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'NLP/js/main.js' %}"></script>
</body>
</html>

NLP/templates/profiles/new.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container">

</div>
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit">Save changes</button>
      </form>
{% endblock %}